title: "Berkhan Berkdemir's blog"
author: Berkhan Berkdemir
description: "About Ruby on Rails, Docker, GitHub, Amazon Web Services, and other cool stuffs"

url: "https://berkhanberkdemir.com"

github_username: BerkhanBerkdemir
rss: RSS

plugins:
- jekyll-feed
- jekyll-sitemap
- jemoji

# Jekyll SEO tag
## DOC: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
twitter:
  username: ' '
  card: summary

social:
  name: Berkhan Berkdemir
  links:
  - https://github.com/BerkhanBerkdemir

# Build settings
markdown: kramdown
theme: minima
sass:
  style: compressed
