github_username: berkhanberkdemir
linkedin_username: berkhanberkdemir
twitter_username: berkhanberkdemi
rss: RSS

plugins:
  - jekyll-archives
  - jekyll-avatar
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

# Jekyll SEO tag
# DOC: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
#
title: Berkhan's Blog
description: A blog dedicated to reviewing any software technology
url: https://www.berkhanberkdemir.com
author:
  name: Berkhan Berkdemir
  twitter: berkhanberkdemi
logo: favicon.ico
twitter:
  username: berkhanberkdemi
  card: summary
social:
  name: Berkhan Berkdemir
  links:
    - https://github.com/berkhanberkdemir
    - https://twitter.com/berkhanberkdemi
    - https://www.linkedin.com/in/berkhanberkdemir

# Build settings
markdown: kramdown
theme: minima
sass:
  style: compressed

collections:
  - newsletters
