name: Jekyll deploy

# NOTE: I'll high likely want to see a preview with chaning NETLIFY_ENVIRONMENT
#    dynamicaly. This can be done with adding `if' statments and checking the
#    required conditon. However, I just don't want to add 3-4 lines reapted
#    code.

on:
  push:
    branches:
      - master

env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: 0bde7ff5-a467-4cff-ba56-5e0159febd36

jobs:
  deploy:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.5"
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
      - run: gem install bundler:1.17.3
      - run: bundler install --path vendor/bundle
      - run: npm install -g netlify-cli
      - run: bundler exec jekyll build
      - run: netlify deploy --dir=_site --prod
