name: Jekyll deploy

on: push

jobs:
  deploy:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.5"
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
      - run: |
          sudo apt-get --yes --no-install-recommends zlib1g-dev
          sudo gem install bundler --version=1.17.3
      - run: bundler install --path vendor/bundle
      - run: bundler exec jekyll build
